import type {FastifyInstance} from "fastify";
import bcrypt from "bcryptjs";
import {z} from "zod";
import {pool} from "../db/pool.js";
const registerSchema=z.object({email:z.string().email().transform(v=>v.toLowerCase().trim()),password:z.string().min(8).max(72),name:z.string().trim().min(2).max(80).optional()});
const loginSchema=z.object({email:z.string().email().transform(v=>v.toLowerCase().trim()),password:z.string().min(1).max(72)});
export async function authRoutes(app:FastifyInstance){
app.post("/register",async(request,reply)=>{const parsed=registerSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"Dados inválidos",details:parsed.error.flatten().fieldErrors});const {email,password,name=""}=parsed.data;const client=await pool.connect();try{await client.query("BEGIN");const exists=await client.query("SELECT id FROM users WHERE email=$1",[email]);if(exists.rowCount)return reply.code(409).send({error:"Este e-mail já está cadastrado"});const hash=await bcrypt.hash(password,12);const result=await client.query("INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id,email,created_at",[email,hash]);const user=result.rows[0];await client.query("INSERT INTO profiles(user_id,name) VALUES($1,$2)",[user.id,name]);await client.query("INSERT INTO notification_preferences(user_id) VALUES($1)",[user.id]);await client.query("COMMIT");const token=app.jwt.sign({sub:user.id,email:user.email},{expiresIn:"7d"});return reply.code(201).send({user,token});}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}});
app.post("/login",async(request,reply)=>{const parsed=loginSchema.safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:"E-mail ou senha inválidos"});const {email,password}=parsed.data;const result=await pool.query("SELECT id,email,password_hash,created_at FROM users WHERE email=$1",[email]);const user=result.rows[0];if(!user||!(await bcrypt.compare(password,user.password_hash)))return reply.code(401).send({error:"E-mail ou senha inválidos"});const token=app.jwt.sign({sub:user.id,email:user.email},{expiresIn:"7d"});return {user:{id:user.id,email:user.email,created_at:user.created_at},token};});
app.get("/me",async(request,reply)=>{try{await request.jwtVerify();const userId=(request.user as {sub:string}).sub;const result=await pool.query("SELECT u.id,u.email,u.created_at,p.name,p.avatar_url,p.timezone FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE u.id=$1",[userId]);if(!result.rowCount)return reply.code(404).send({error:"Usuário não encontrado"});return {user:result.rows[0]};}catch{return reply.code(401).send({error:"Não autenticado"})}});
}